#!/usr/bin/env bash
# ==========================================
#   🚀 Tyrkrox_gamer - ALL IN ONE TOOL
# ==========================================

set -u

C=$'\033[36m'
G=$'\033[32m'
R=$'\033[31m'
B=$'\033[34m'
Y=$'\033[33m'
W=$'\033[97m'
N=$'\033[0m'

header() {
    clear
    echo -e "${B}=====================================================${N}"
    echo -e "${Y}      🚀 Tyrkrox_gamer - ALL IN ONE TOOL${N}"
    echo -e "${B}=====================================================${N}"
    echo ""
}

pause() {
    echo ""
    read -p "Press [Enter] to return to menu..." dummy
}

while true; do
    header
    echo -e "${C} 1) ${W}Discord Server Link${N}"
    echo -e "${C} 2) ${W}YouTube Channel Link${N}"
    echo -e "${C} 3) ${W}Vm/Kvm Installer${N}"
    echo -e "${C} 4) ${W}Pterodactyl Panel + Wings${N}"
    echo -e "${C} 5) ${W}Blueprint + Addon${N}"
    echo -e "${C} 6) ${W}SFTP Fixer${N}"
    echo -e "${C} 7) ${W}Tailscale Installer${N}"
    echo -e "${C} 8) ${W}Proxmox Docker Installer${N}"
    echo -e "${R} 9) Exit${N}"
    echo ""
    read -p "Select option [1-9]: " choice

    case $choice in
        1)
            echo "https://discord.gg/2rYEHharqA"
            pause ;;
        2)
            echo "https://youtube.com/@tyrkrox_gamer"
            pause ;;
        3)
            bash <(curl -fsSL https://raw.githubusercontent.com/OfficialCodesHub/NOTHING/main/001)
            pause ;;
        4)
            bash <(curl -s https://pterodactyl-installer.se)
            pause ;;
        5)
            bash <(curl -fsSL https://raw.githubusercontent.com/OfficialCodesHub/NOTHING/main/002)
            pause ;;
        6)
            bash <(curl -fsSL https://raw.githubusercontent.com/OfficialCodesHub/NOTHING/main/ssh.sh)
            pause ;;
        7)
            curl -fsSL https://tailscale.com/install.sh | sh
            pause ;;
        8)
            docker run -itd \
            --name proxmoxve \
            --hostname pve \
            --privileged \
            -p 8006:8006 \
            rtedpro/proxmox:9.0.11
            pause ;;
        9)
            echo "Exiting..."
            exit 0 ;;
        *)
            echo "Invalid Option!"
            sleep 2 ;;
    esac
done
